run:
  job: evaluate
  eval_mode: ensemble
  experiment_directory: ./saved_experiments
  save_model: false
  gpu: 0
  eval_experiment_name: ugnn_classification
  experiment_name: ugnn_ood_budget
data:
  split_no: 1
  dataset: CoraML
  root: ./data
  ood_flag: true
  train_samples_per_class: 0.05
  val_samples_per_class: 0.15
  test_samples_per_class: 0.8
  split: random
  ood_setting: evasion
  ood_type: perturb_features
  ood_dataset_type: budget
  ood_budget_per_graph: 0.1
  ood_perturbation_type: not_normalized
  ood_noise_scale: 1.0
model:
  seed: 42
  init_no: 1
  model_name: GCN
  dim_hidden: 64
  dropout_prob: 0.8
  dropout_prob_adj: 0.0
  ensemble_min_init_no: 1
  ensemble_max_init_no: 10
training:
  epochs: 100000
  stopping_mode: default
  stopping_patience: 50
  stopping_restore_best: true
  stopping_metric: val_CE
  stopping_minimize: true
  lr: 0.01
  weight_decay: 0.0001
